### ISSUE TITLE
Fatal error if path contains non-UTF8 characters

### ISSUE THREAD

**Issue by mariusmandal** [dropbox/dropbox-sdk-php#44] opened 2016-05-04 13:37 UTC
If path contains non-UTF8 characters it tries to throw an exception, but PHP fails with fatal error.

Given following path
`/_Fylkesmønstringen (PLID4060)/Silje �rseth Russenes.jpg`

PHP returns
`Fatal error: in /dropbox-sdk/lib/Dropbox/Path.php on line 171`

Not sure if this is the best solution, but it fixed it for me:
Replaced line 169
```
        if ($error !== null) throw new \InvalidArgumentException("'$argName'': bad path: $error: ".var_export($value, true));
```
With
```
        if ( $error !== null ) {
               if( 0 === strpos( $error, 'must be valid UTF-8' ) ) throw new \InvalidArgumentException("'$argName': bad path: $error");
                throw new \InvalidArgumentException("'$argName': bad path: $error: ". var_export( $value, true ));
        }

**Comment by greg-db** [comment] 2016-05-04 17:41
Thanks for the report @mariusmandal ! Can you share some sample code that reproduces the issue?

**Comment by cakoose** [comment] 2016-05-04 19:02
I wasn't able to reproduce the problem locally.  I wonder if there's some locale-specific behavior coming into play.

Either way, we really should be escaping special characters.  Since `var_export` doesn't do that, I modified the code to do it manually.  I committed the change to the "path-escape" branch; can you try it out and let me know if it fixed the problem?

**Comment by cakoose** [comment] 2016-05-09 08:17
@mariusmandal Did you get a chance to test the "path-escape" branch?

**Comment by mariusmandal** [comment] 2016-05-10 08:33
Been on vacation, will test during this week

**Comment by cakoose** [comment] 2016-06-15 00:07
I committed the fix, so I'm closing the issue.  Please re-open if it's not fixed for you.

**Closed by cakoose** 2016-06-15 00:07 UTC
